# Generated by Django 4.2.3 on 2023-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaudio',
            name='description',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.DeleteModel(
            name='MyAudioSegment',
        ),
    ]
