# Generated by Django 4.2.3 on 2023-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_myaudio_description_delete_myaudiosegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAudiomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='my_audio')),
            ],
        ),
    ]
