# Generated by Django 4.2.4 on 2023-08-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_audio_audiosegment_delete_myaudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiosegment',
            old_name='name',
            new_name='audio_id',
        ),
    ]
