# Generated by Django 4.2.4 on 2023-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0005_rename_name_audiosegment_audio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='my_audio')),
                ('description', models.TextField(max_length=100000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='audiosegment',
            name='audio_id',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='AudioSegment',
        ),
    ]
