# Generated by Django 4.2.4 on 2023-08-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0006_myaudio_remove_audiosegment_audio_id_delete_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaudio',
            name='end_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='myaudio',
            name='start_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='myaudiomain',
            name='description',
            field=models.TextField(max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='myaudio',
            name='audio_file',
            field=models.FileField(upload_to='segment'),
        ),
    ]
