# Generated by Django 4.2.4 on 2023-08-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0007_myaudio_end_time_myaudio_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaudio',
            name='description',
        ),
    ]
