# Generated by Django 4.2.4 on 2023-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0008_remove_myaudio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaudio',
            name='name',
        ),
        migrations.AddField(
            model_name='myaudio',
            name='description',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
