# Generated by Django 4.2.4 on 2023-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0009_remove_myaudio_name_myaudio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaudiomain',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
