# Generated by Django 4.2.4 on 2023-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0011_rename_audio_file_myaudiomain_audiofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myaudiomain',
            old_name='filename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='myaudiomain',
            name='audioFile',
        ),
        migrations.AddField(
            model_name='myaudiomain',
            name='audio_file',
            field=models.FileField(null=True, upload_to='my_audio'),
        ),
    ]
