# Generated by Django 4.2.4 on 2023-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0012_rename_filename_myaudiomain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaudiomain',
            name='audio_file',
            field=models.FileField(upload_to='my_audio'),
        ),
    ]
