# Generated by Django 4.2.4 on 2023-08-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0013_alter_myaudiomain_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaudiomain',
            name='audio_file',
            field=models.FileField(null=True, upload_to='my_audio'),
        ),
    ]
