# Generated by Django 4.2.4 on 2023-08-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0015_jsondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMainAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('audio_file', models.FileField(null=True, upload_to='my_audio')),
                ('description', models.TextField(max_length=10000000, null=True)),
            ],
        ),
    ]
